---
# Fichier de paramètres pour Oracle Linux 8

vm_min_free_kbytes: "{{ ([1048576, ((0.5 / 100 * ansible_memtotal_mb) * 1024) | round | int] | max) }}"

linux_packages:
  - bc
  - bind-libs
  - bind-libs-lite
  - bind-license
  - bind-utils
  - binutils
  - chrony
  - elfutils-libelf
  - elfutils-libelf-devel
  - fontconfig-devel
  - fstrm
  - gcc
  - glibc
  - glibc-devel
  - glibc-devel.i686
  - glibc-headers
  - gssproxy
  - htop
  - kernel-headers
  - keyutils
  - ksh
  - libaio
  - libaio.i686
  - libaio-devel
  - libaio-devel.i686
  - libdmx
  - libgcc
  - libgcc.i686
  - libibverbs
  - libICE
  - libmaxminddb
  - libnsl
  - libpkgconf
  - librdmacm
  - libSM
  - libstdc++.i686
  - libstdc++
  - libstdc++-devel
  - libstdc++-devel.i686
  - libverto-libevent
  - libX11
  - libX11-common
  - libX11-xcb
  - libXau
  - libxcb
  - libXcomposite
  - libxcrypt-devel
  - libXext
  - libXi
  - libXi.i686
  - libXinerama
  - libXmu
  - libXrandr
  - libXrender
  - libXt
  - libXtst
  - libXtst.i686
  - libXv
  - libXxf86dga
  - libXxf86misc
  - libXxf86vm
  - lm_sensors-libs
  - make
  - mlocate
  - nscd
  - net-snmp
  - net-tools
  - nfs-utils
  - perl
  - pkgconf
  - pkgconf-m4
  - pkgconf-pkg-config
  - policycoreutils
  - policycoreutils-python-utils
  - protobuf-c
  - psmisc
  - python3-bind
  - python3-pyyaml
  - quota
  - quota-nls
  - rpcbind
  - rsync
  - rlwrap
  - smartmontools
  - sysstat
  - tar
  - tmux
  - tree
  - unixODBC
  - unixODBC-devel
  - unzip
  - vim
  - vim-enhanced
  - wget
  - xorg-x11-utils
  - xorg-x11-xauth
  - numactl
  - rsyslog
