---
# Fichier de paramètres pour Oracle Linux 7
# vm_min_free_kbytes non défini : oracle_sysconfig utilise le défaut 524288

linux_packages:
  - bc
  - bind-libs
  - bind-libs-lite
  - bind-license
  - bind-utils
  - binutils
  - btrfs-progs
  - chrony
  - compat-libcap1
  - compat-libstdc++-33
  - cpp
  - deltarpm
  - device-mapper-multipath
  - elfutils-libelf
  - elfutils-libelf-devel
  - ethtool
  - fontconfig-devel
  - fstrm
  - gcc
  - gcc-c++
  - glibc
  - glibc-devel
  - glibc-devel.i686
  - glibc-headers
  - gssproxy
  - htop
  - kernel-headers
  - keyutils
  - ksh
  - libaio
  - libaio-devel
  - libdmx
  - libgcc
  - libibverbs
  - libICE
  - libmaxminddb
  - librdmacm
  - libselinux-python
  - libSM
  - libstdc++
  - libstdc++-devel
  - libtool-ltdl
  - libverto-libevent
  - libX11
  - libX11-common
  - libXau
  - libxcb
  - libXext
  - libXi
  - libXinerama
  - libXmu
  - libXp
  - libXrandr
  - libXrender
  - libXrender-devel
  - libXt
  - libXtst
  - libXv
  - libXxf86dga
  - libXxf86misc
  - libXxf86vm
  - lm_sensors-libs
  - lsof
  - lvm2
  - make
  - mlocate
  - module-init-tools
  - mpfr
  - ncurses
  - ncurses-devel
  - ncurses-libs
  - net-snmp
  - net-tools
  - nfs-utils
  - nmap
  - nscd
  - ntp
  - openssh-clients
  - parted
  - perl
  - policycoreutils
  - policycoreutils-python
  - procps
  - protobuf-c
  - psmisc
  - quota
  - quota-nls
  - readline
  - readline-devel
  - rlwrap
  - rsync
  - rpcbind
  - sg3_utils
  - smartmontools
  - sysstat
  - system-storage-manager
  - tar
  - tree
  - unixODBC
  - unixODBC-devel
  - unzip
  - util-linux-ng
  - vim
  - vim-enhanced
  - wget
  - xdpyinfo
  - xfsprogs
  - xorg-x11-server-utils
  - xorg-x11-utils
  - xorg-x11-xauth
  - xorg-x11-xinit
  - xterm
  - yum-utils
