---
- name: Vérifier les prérequis pour la post-installation
  ansible.builtin.assert:
    that:
      - ansible_memtotal_mb >= 2048
    msg: "Prérequis non satisfaits : RAM >= 2GB"
  tags: prerequisites

- ansible.builtin.include_tasks: validations.yml
  tags: prerequisites

- ansible.builtin.include_tasks: scripts.yml
  tags: scripts

- ansible.builtin.include_tasks: backup.yml
  tags: backup

- ansible.builtin.include_tasks: services.yml
  tags: [dbora_init, oracle_cleaner, logrotate]
