---
oracle_binary_url: "https://kutt.axiome.io/db19300"
oracle_zip_filename: "V982063-01_Oracle_Database_19.3.0.0.0_for_Linux_x86-64.zip"

opatch_download_url: "https://kutt.axiome.io/opatch"
opatch_file: "p6880880_190000_Linux-x86-64_OPatch_12.2.0.1.51.zip"

psu_download_url: "https://kutt.axiome.io/db_ru"
psu_file: "p39034528_190000_Linux-x86-64_DBRU_19.31.zip"

db_template_version_string: "19.0.0"
