---
- name: Configuration grub - Suppression des args inutiles
  ansible.builtin.shell: grubby --update-kernel=ALL --remove-args={{ item }}
  loop:
    - rhgb
    - quiet
  changed_when: true
  tags: grub

- name: Configuration grub - Ajout des args Oracle
  ansible.builtin.shell: grubby --update-kernel=ALL --args={{ item }}
  loop:
    - transparent_hugepage=never
    - numa=off
    - elevator=deadline
    - vga=791
  changed_when: true
  tags: grub
