---
  # ---------------------------------------------------
  # installation de l'utilitaire rlwrap pour oracle
  # ---------------------------------------------------

  # ajout du repository epel si non présent
  - name: YUM - installation du paquet oracle-epel-release
    yum:  name="oracle-epel-release-el{{ ansible_distribution_major_version }}" state=latest disable_gpg_check=yes
    tags: install_epel

  # installation rlwrap depuis le repo epel
  - name: YUM - installation de rlwrap
    yum:  name=rlwrap state=latest disable_gpg_check=yes
    tags: rlwrap

  # suppression du repo epel car il n'est plus necessaire
  - name: YUM - désinstallation du paquet oracle-epel-release
    yum:  name="oracle-epel-release-el{{ ansible_distribution_major_version }}" state=absent disable_gpg_check=yes
    tags: install_epel
