---
  # ---------------------------------------------------
  # installation de packages supplémentaires rlwrap et htop
  # ---------------------------------------------------

  # ajout du repository epel si non présent
  - name: YUM - installation du paquet oracle-epel-release
    yum:  name="oracle-epel-release-el{{ ansible_distribution_major_version }}" state=latest disable_gpg_check=yes
    tags: install_epel
    # when: ansible_distribution_major_version == '9'

  # installation rlwrap depuis le repo epel
  - name: YUM - installation de packages supplémentaires
    yum:  name={{ item }} state=latest disable_gpg_check=yes
    with_items:
      - rlwrap
      - htop
      - nmap
      - strace
      - tcpdump
      - lsof
    # when: ansible_distribution_major_version == '9'

  # suppression du repo epel car il n'est plus necessaire
  - name: YUM - désinstallation du paquet oracle-epel-release
    yum:  name="oracle-epel-release-el{{ ansible_distribution_major_version }}" state=absent disable_gpg_check=yes
    tags: install_epel
    # when: ansible_distribution_major_version == '9'
