---
- name: "Chargement des variables pour Oracle {{ oracle_version }}"
  ansible.builtin.include_vars: "{{ oracle_version }}.yml"

- name: Vérifier les prérequis pour l'installation
  ansible.builtin.assert:
    that:
      - ansible_memtotal_mb >= 2048
      - ansible_processor_vcpus >= 2
    msg: "Prérequis non satisfaits pour Oracle : RAM >= 2GB, CPU >= 2"
  tags: prerequisites

- name: "Installation Oracle Database {{ oracle_version }}"
  ansible.builtin.include_tasks: install-db.yml
